const searchTerms = [
  "80s future tech predictions",
  "80s future tech predictions deep dive",
  "80s future tech predictions vs analog glitch art",
  "80s future tech predictions vs daytona usa racing",
  "80s future tech predictions vs porsche 911 1964",
  "ac cobra",
  "ac cobra deep dive",
  "ac cobra vs nissan skyline gt-r r32",
  "amc javelin",
  "amc javelin deep dive",
  "analog cyberdeck builds",
  "analog cyberdeck builds deep dive",
  "analog glitch art",
  "analog glitch art deep dive",
  "angelfire spellbook page",
  "angelfire spellbook page deep dive",
  "animated under construction",
  "animated under construction deep dive",
  "animated under construction vs vhs rewind dream",
  "ant farm escape",
  "ant farm escape deep dive",
  "ant farm escape vs internet dead theory",
  "area 51 alien files",
  "area 51 alien files deep dive",
  "ascii art bbs",
  "ascii art bbs deep dive",
  "ascii art bbs vs mercedes 190e cosworth",
  "aston martin db5",
  "aston martin db5 deep dive",
  "aston martin db5 vs lamborghini diablo",
  "aston martin db5 vs liminal spaces images",
  "aston martin db5 vs lucky star cursor trail",
  "audi quattro sport",
  "audi quattro sport deep dive",
  "autoexec.bat hacks",
  "autoexec.bat hacks deep dive",
  "backrooms explained",
  "backrooms explained deep dive",
  "backrooms explained vs porsche 959",
  "blade runner neon tokyo",
  "blade runner neon tokyo deep dive",
  "blinking html tag",
  "blinking html tag deep dive",
  "blinking html tag vs maserati ghibli",
  "bmw 3.0 csl batmobile",
  "bmw 3.0 csl batmobile deep dive",
  "bmw 3.0 csl batmobile vs porsche 911 carrera rs",
  "bmw 3.0 csl batmobile vs windows 95 horror aesthetic",
  "bmw m3 e30",
  "bmw m3 e30 deep dive",
  "bmw m3 e30 vs jaguar e-type series 1",
  "bmw m3 e30 vs johnny mnemonic internet",
  "bugatti eb110",
  "bugatti eb110 deep dive",
  "cassette data storage",
  "cassette data storage deep dive",
  "chevrolet corvette sting ray",
  "chevrolet corvette sting ray deep dive",
  "codec artifacts aesthetic",
  "codec artifacts aesthetic deep dive",
  "codec artifacts aesthetic vs animated under construction",
  "corrupted rom art",
  "corrupted rom art deep dive",
  "creepy crawlers oven",
  "creepy crawlers oven deep dive",
  "creepy crawlers oven vs ferrari f40",
  "crt terminal hacking",
  "crt terminal hacking deep dive",
  "crt terminal hacking vs bmw 3.0 csl batmobile",
  "crt terminal hacking vs internet dead theory",
  "datamosh tutorial",
  "datamosh tutorial deep dive",
  "datamosh tutorial vs virtua cop cabinet",
  "datsun 240z",
  "datsun 240z deep dive",
  "datsun 240z vs windows 3.11 games",
  "daytona usa racing",
  "daytona usa racing deep dive",
  "de tomaso pantera",
  "de tomaso pantera deep dive",
  "de tomaso pantera vs zelda cdi cutscenes",
  "demolition man future",
  "demolition man future deep dive",
  "dialup telnet sessions",
  "dialup telnet sessions deep dive",
  "dialup telnet sessions vs scsi terminator plugs",
  "doom config sys",
  "doom config sys deep dive",
  "dot matrix printer sound",
  "dot matrix printer sound deep dive",
  "dot matrix printer sound vs honda nsx",
  "double dragon co-op",
  "double dragon co-op deep dive",
  "double dragon co-op vs autoexec.bat hacks",
  "double dragon co-op vs peugeot 205 gti",
  "ferrari 250 gto",
  "ferrari 250 gto deep dive",
  "ferrari 512BB",
  "ferrari 512BB deep dive",
  "ferrari 512BB vs porsche 959",
  "ferrari 512BB vs toyota celica gt",
  "ferrari f40",
  "ferrari f40 deep dive",
  "ferrari f40 vs dialup telnet sessions",
  "fifth element fashion",
  "fifth element fashion deep dive",
  "final fight beat em up",
  "final fight beat em up deep dive",
  "floppy disk bootloader",
  "floppy disk bootloader deep dive",
  "floppy disk bootloader vs windows 3.11 games",
  "ford gt40 le mans",
  "ford gt40 le mans deep dive",
  "ford mustang fastback",
  "ford mustang fastback deep dive",
  "ford mustang fastback vs sonic inflation deviantart",
  "ford sierra cosworth",
  "ford sierra cosworth deep dive",
  "gameboy camera nightmare",
  "gameboy camera nightmare deep dive",
  "gameboy camera nightmare vs subaru impreza 22b",
  "geocities occult shrine",
  "geocities occult shrine deep dive",
  "grow your own crystal",
  "grow your own crystal deep dive",
  "hackers movie soundtrack",
  "hackers movie soundtrack deep dive",
  "hackers movie soundtrack vs sonic debug mode",
  "history of 80s future tech predictions",
  "history of ac cobra",
  "history of amc javelin",
  "history of analog cyberdeck builds",
  "history of analog glitch art",
  "history of angelfire spellbook page",
  "history of animated under construction",
  "history of ant farm escape",
  "history of area 51 alien files",
  "history of ascii art bbs",
  "history of aston martin db5",
  "history of audi quattro sport",
  "history of autoexec.bat hacks",
  "history of backrooms explained",
  "history of blade runner neon tokyo",
  "history of blinking html tag",
  "history of bmw 3.0 csl batmobile",
  "history of bmw m3 e30",
  "history of bugatti eb110",
  "history of cassette data storage",
  "history of chevrolet corvette sting ray",
  "history of codec artifacts aesthetic",
  "history of corrupted rom art",
  "history of creepy crawlers oven",
  "history of crt terminal hacking",
  "history of datamosh tutorial",
  "history of datsun 240z",
  "history of daytona usa racing",
  "history of de tomaso pantera",
  "history of demolition man future",
  "history of dialup telnet sessions",
  "history of doom config sys",
  "history of dot matrix printer sound",
  "history of double dragon co-op",
  "history of ferrari 250 gto",
  "history of ferrari 512BB",
  "history of ferrari f40",
  "history of fifth element fashion",
  "history of final fight beat em up",
  "history of floppy disk bootloader",
  "history of ford gt40 le mans",
  "history of ford mustang fastback",
  "history of ford sierra cosworth",
  "history of gameboy camera nightmare",
  "history of geocities occult shrine",
  "history of grow your own crystal",
  "history of hackers movie soundtrack",
  "history of honda nsx",
  "history of hyperrealistic garfield",
  "history of insert coin nostalgia",
  "history of internet dead theory",
  "history of iso grifo",
  "history of jaguar e-type series 1",
  "history of jetsons real life gadgets",
  "history of johnny mnemonic internet",
  "history of lamborghini countach lp400",
  "history of lamborghini diablo",
  "history of lamborghini miura",
  "history of lancia delta integrale evo",
  "history of lancia stratos",
  "history of laserdisc educational video",
  "history of lawnmower man vr",
  "history of liminal spaces images",
  "history of lotus esprit s1",
  "history of lotus esprit v8",
  "history of lucky star cursor trail",
  "history of mandela effect examples",
  "history of maserati ghibli",
  "history of mazda rx-7 fd",
  "history of mentos coke rocket fail",
  "history of mercedes 190e cosworth",
  "history of midi music autoplay",
  "history of mini disc player 2000s",
  "history of mitsubishi lancer evo vi",
  "history of neo geo mvs cartridges",
  "history of neopets dark guilds",
  "history of nissan skyline gt-r r32",
  "history of norton commander ui",
  "history of opel manta rallye",
  "history of original term 42",
  "history of original term 9",
  "history of outrun arcade machine",
  "history of peugeot 205 gti",
  "history of pontiac gto judge",
  "history of porsche 911 1964",
  "history of porsche 911 carrera rs",
  "history of porsche 959",
  "history of potato clock instructions",
  "history of project mk ultra declassified",
  "history of qbasic gorillas code",
  "history of renault 5 turbo",
  "history of renault alpine a310",
  "history of reptilian shapeshifters",
  "history of robocop prime directives",
  "history of scsi terminator plugs",
  "history of shelby cobra 427",
  "history of shrek vaporwave edit",
  "history of simulation theory reddit",
  "history of slime lab kit explosion",
  "history of sonic debug mode",
  "history of sonic inflation deviantart",
  "history of spy tech voice changer",
  "history of starry gif backgrounds",
  "history of subaru impreza 22b",
  "history of thomas the tank cursed",
  "history of time crisis light gun",
  "history of total recall mars memories",
  "history of toyota celica gt",
  "history of toyota supra mk4",
  "history of trackball mouse ergonomic",
  "history of translucent imac g3",
  "history of turbo button pc",
  "history of tv static memories",
  "history of vhs rewind dream",
  "history of vhs vision of the future",
  "history of virtua cop cabinet",
  "history of wario fanfiction archive",
  "history of wearable tech 1992",
  "history of winamp milkdrop presets",
  "history of windows 3.11 games",
  "history of windows 95 horror aesthetic",
  "history of yakbak prank recorder",
  "history of zelda cdi cutscenes",
  "history of zip drive click of death",
  "honda nsx",
  "honda nsx deep dive",
  "hyperrealistic garfield",
  "hyperrealistic garfield deep dive",
  "hyperrealistic garfield vs wearable tech 1992",
  "insert coin nostalgia",
  "insert coin nostalgia deep dive",
  "insert coin nostalgia vs bmw m3 e30",
  "internet dead theory",
  "internet dead theory deep dive",
  "iso grifo",
  "iso grifo deep dive",
  "jaguar e-type series 1",
  "jaguar e-type series 1 deep dive",
  "jetsons real life gadgets",
  "jetsons real life gadgets deep dive",
  "johnny mnemonic internet",
  "johnny mnemonic internet deep dive",
  "lamborghini countach lp400",
  "lamborghini countach lp400 deep dive",
  "lamborghini diablo",
  "lamborghini diablo deep dive",
  "lamborghini diablo vs lotus esprit v8",
  "lamborghini diablo vs neo geo mvs cartridges",
  "lamborghini diablo vs windows 95 horror aesthetic",
  "lamborghini miura",
  "lamborghini miura deep dive",
  "lancia delta integrale evo",
  "lancia delta integrale evo deep dive",
  "lancia stratos",
  "lancia stratos deep dive",
  "lancia stratos vs floppy disk bootloader",
  "lancia stratos vs mini disc player 2000s",
  "laserdisc educational video",
  "laserdisc educational video deep dive",
  "laserdisc educational video vs amc javelin",
  "laserdisc educational video vs datsun 240z",
  "laserdisc educational video vs floppy disk bootloader",
  "lawnmower man vr",
  "lawnmower man vr deep dive",
  "lawnmower man vr vs demolition man future",
  "liminal spaces images",
  "liminal spaces images deep dive",
  "liminal spaces images vs ferrari 250 gto",
  "lotus esprit s1",
  "lotus esprit s1 deep dive",
  "lotus esprit s1 vs iso grifo",
  "lotus esprit v8",
  "lotus esprit v8 deep dive",
  "lotus esprit v8 vs mini disc player 2000s",
  "lucky star cursor trail",
  "lucky star cursor trail deep dive",
  "mandela effect examples",
  "mandela effect examples deep dive",
  "mandela effect examples vs aston martin db5",
  "maserati ghibli",
  "maserati ghibli deep dive",
  "maserati ghibli vs total recall mars memories",
  "mazda rx-7 fd",
  "mazda rx-7 fd deep dive",
  "mentos coke rocket fail",
  "mentos coke rocket fail deep dive",
  "mentos coke rocket fail vs lotus esprit s1",
  "mentos coke rocket fail vs pontiac gto judge",
  "mercedes 190e cosworth",
  "mercedes 190e cosworth deep dive",
  "midi music autoplay",
  "midi music autoplay deep dive",
  "mini disc player 2000s",
  "mini disc player 2000s deep dive",
  "mini disc player 2000s vs ascii art bbs",
  "mini disc player 2000s vs double dragon co-op",
  "mini disc player 2000s vs midi music autoplay",
  "mitsubishi lancer evo vi",
  "mitsubishi lancer evo vi deep dive",
  "neo geo mvs cartridges",
  "neo geo mvs cartridges deep dive",
  "neopets dark guilds",
  "neopets dark guilds deep dive",
  "nissan skyline gt-r r32",
  "nissan skyline gt-r r32 deep dive",
  "nissan skyline gt-r r32 vs datamosh tutorial",
  "nissan skyline gt-r r32 vs gameboy camera nightmare",
  "nissan skyline gt-r r32 vs simulation theory reddit",
  "norton commander ui",
  "norton commander ui deep dive",
  "opel manta rallye",
  "opel manta rallye deep dive",
  "original term 42",
  "original term 42 deep dive",
  "original term 42 vs project mk ultra declassified",
  "original term 9",
  "original term 9 deep dive",
  "original term 9 vs simulation theory reddit",
  "outrun arcade machine",
  "outrun arcade machine deep dive",
  "outrun arcade machine vs aston martin db5",
  "peugeot 205 gti",
  "peugeot 205 gti deep dive",
  "pontiac gto judge",
  "pontiac gto judge deep dive",
  "porsche 911 1964",
  "porsche 911 1964 deep dive",
  "porsche 911 1964 vs neo geo mvs cartridges",
  "porsche 911 carrera rs",
  "porsche 911 carrera rs deep dive",
  "porsche 959",
  "porsche 959 deep dive",
  "potato clock instructions",
  "potato clock instructions deep dive",
  "project mk ultra declassified",
  "project mk ultra declassified deep dive",
  "project mk ultra declassified vs ferrari 250 gto",
  "project mk ultra declassified vs wario fanfiction archive",
  "qbasic gorillas code",
  "qbasic gorillas code deep dive",
  "qbasic gorillas code vs original term 42",
  "renault 5 turbo",
  "renault 5 turbo deep dive",
  "renault 5 turbo vs windows 3.11 games",
  "renault 5 turbo vs yakbak prank recorder",
  "renault alpine a310",
  "renault alpine a310 deep dive",
  "reptilian shapeshifters",
  "reptilian shapeshifters deep dive",
  "robocop prime directives",
  "robocop prime directives deep dive",
  "robocop prime directives vs project mk ultra declassified",
  "scsi terminator plugs",
  "scsi terminator plugs deep dive",
  "scsi terminator plugs vs honda nsx",
  "shelby cobra 427",
  "shelby cobra 427 deep dive",
  "shelby cobra 427 vs jetsons real life gadgets",
  "shelby cobra 427 vs scsi terminator plugs",
  "shrek vaporwave edit",
  "shrek vaporwave edit deep dive",
  "simulation theory reddit",
  "simulation theory reddit deep dive",
  "simulation theory reddit vs aston martin db5",
  "simulation theory reddit vs internet dead theory",
  "slime lab kit explosion",
  "slime lab kit explosion deep dive",
  "sonic debug mode",
  "sonic debug mode deep dive",
  "sonic inflation deviantart",
  "sonic inflation deviantart deep dive",
  "sonic inflation deviantart vs daytona usa racing",
  "sonic inflation deviantart vs ferrari 250 gto",
  "sonic inflation deviantart vs lamborghini miura",
  "spy tech voice changer",
  "spy tech voice changer deep dive",
  "starry gif backgrounds",
  "starry gif backgrounds deep dive",
  "subaru impreza 22b",
  "subaru impreza 22b deep dive",
  "subaru impreza 22b vs datsun 240z",
  "thomas the tank cursed",
  "thomas the tank cursed deep dive",
  "thomas the tank cursed vs mazda rx-7 fd",
  "time crisis light gun",
  "time crisis light gun deep dive",
  "time crisis light gun vs outrun arcade machine",
  "total recall mars memories",
  "total recall mars memories deep dive",
  "total recall mars memories vs ac cobra",
  "toyota celica gt",
  "toyota celica gt deep dive",
  "toyota celica gt vs analog cyberdeck builds",
  "toyota celica gt vs ferrari f40",
  "toyota supra mk4",
  "toyota supra mk4 deep dive",
  "trackball mouse ergonomic",
  "trackball mouse ergonomic deep dive",
  "translucent imac g3",
  "translucent imac g3 deep dive",
  "translucent imac g3 vs blinking html tag",
  "turbo button pc",
  "turbo button pc deep dive",
  "tv static memories",
  "tv static memories deep dive",
  "tv static memories vs area 51 alien files",
  "tv static memories vs internet dead theory",
  "vhs rewind dream",
  "vhs rewind dream deep dive",
  "vhs vision of the future",
  "vhs vision of the future deep dive",
  "vhs vision of the future vs floppy disk bootloader",
  "vhs vision of the future vs lamborghini diablo",
  "vhs vision of the future vs lawnmower man vr",
  "vhs vision of the future vs liminal spaces images",
  "virtua cop cabinet",
  "virtua cop cabinet deep dive",
  "wario fanfiction archive",
  "wario fanfiction archive deep dive",
  "wearable tech 1992",
  "wearable tech 1992 deep dive",
  "wearable tech 1992 vs angelfire spellbook page",
  "wearable tech 1992 vs vhs vision of the future",
  "winamp milkdrop presets",
  "winamp milkdrop presets deep dive",
  "winamp milkdrop presets vs backrooms explained",
  "winamp milkdrop presets vs doom config sys",
  "windows 3.11 games",
  "windows 3.11 games deep dive",
  "windows 3.11 games vs gameboy camera nightmare",
  "windows 95 horror aesthetic",
  "windows 95 horror aesthetic deep dive",
  "yakbak prank recorder",
  "yakbak prank recorder deep dive",
  "yakbak prank recorder vs autoexec.bat hacks",
  "zelda cdi cutscenes",
  "zelda cdi cutscenes deep dive",
  "zelda cdi cutscenes vs ferrari f40",
  "zelda cdi cutscenes vs insert coin nostalgia",
  "zip drive click of death",
  "zip drive click of death deep dive",
  
  // Space Race & Sci-Fi Classics
  "apollo missions moon landing",
  "apollo missions moon landing deep dive",
  "apollo missions moon landing vs blade runner replicants",
  "space shuttle challenger disaster",
  "space shuttle challenger disaster deep dive",
  "space shuttle challenger disaster vs aliens marines",
  "mars rover curiosity",
  "mars rover curiosity deep dive",
  "mars rover curiosity vs robocop directives",
  
  // Cold War Tech & Sci-Fi Shows
  "stealth bomber f117 nighthawk",
  "stealth bomber f117 nighthawk deep dive",
  "stealth bomber f117 nighthawk vs knight rider kitt",
  "sdi star wars defense",
  "sdi star wars defense deep dive",
  "sdi star wars defense vs airwolf helicopter",
  "soviet mir space station",
  "soviet mir space station deep dive",
  "soviet mir space station vs street hawk bike",
  
  // Early Internet & Operating Systems
  "usenet alt groups",
  "usenet alt groups deep dive",
  "usenet alt groups vs os2 warp",
  "irc channel operators",
  "irc channel operators deep dive",
  "irc channel operators vs beos operating system",
  "ftp anonymous sites",
  "ftp anonymous sites deep dive",
  "ftp anonymous sites vs amiga workbench",
  
  // Synthwave & Digital Art
  "kavinsky outrun soundtrack",
  "kavinsky outrun soundtrack deep dive",
  "kavinsky outrun soundtrack vs pixel art sprites",
  "perturbator dangerous days",
  "perturbator dangerous days deep dive",
  "perturbator dangerous days vs ascii art banners",
  "carpenter brut trilogy",
  "carpenter brut trilogy deep dive",
  "carpenter brut trilogy vs early cgi rendering",
  
  // UFO Discovery
  "ufo roswell crash",
  "ufo roswell crash deep dive",
  "ufo roswell crash vs mars rover curiosity",
  
  // Hackers History & Infamous Events
  "kevin mitnick capture",
  "kevin mitnick capture deep dive",
  "kevin mitnick capture vs morris worm internet",
  "morris worm internet",
  "morris worm internet deep dive",
  "morris worm internet vs cih chernobyl virus",
  "cih chernobyl virus",
  "cih chernobyl virus deep dive",
  "cih chernobyl virus vs melissa email virus",
  "melissa email virus",
  "melissa email virus deep dive",
  "melissa email virus vs iloveyou virus",
  "iloveyou virus",
  "iloveyou virus deep dive",
  "iloveyou virus vs code red worm",
  "code red worm",
  "code red worm deep dive",
  "code red worm vs nimda virus",
  "nimda virus",
  "nimda virus deep dive",
  "nimda virus vs slammer sql worm",
  "slammer sql worm",
  "slammer sql worm deep dive",
  "slammer sql worm vs conficker worm",
  "conficker worm",
  "conficker worm deep dive",
  "conficker worm vs stuxnet iran",
  "stuxnet iran",
  "stuxnet iran deep dive",
  "stuxnet iran vs wannacry ransomware",
  "wannacry ransomware",
  "wannacry ransomware deep dive",
  "wannacry ransomware vs notpetya cyberattack",
  "notpetya cyberattack",
  "notpetya cyberattack deep dive",
  "notpetya cyberattack vs equifax data breach",
  "equifax data breach",
  "equifax data breach deep dive",
  "equifax data breach vs solarwinds hack",
  "solarwinds hack",
  "solarwinds hack deep dive",
  "solarwinds hack vs colonial pipeline ransomware",
  "colonial pipeline ransomware",
  "colonial pipeline ransomware deep dive",
  "colonial pipeline ransomware vs log4j vulnerability",
  "log4j vulnerability",
  "log4j vulnerability deep dive",
  "log4j vulnerability vs zeroday exploits",
  "zeroday exploits",
  "zeroday exploits deep dive",
  "zeroday exploits vs phishing attacks",
  "phishing attacks",
  "phishing attacks deep dive",
  "phishing attacks vs social engineering",
  "social engineering",
  "social engineering deep dive",
  "social engineering vs kevin mitnick capture",
];
